// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnhGJO2oVueXwGtKiJInAnk2hKnUFNN0I',
    appId: '1:534458459636:web:4b7b2ac7423443ebe9c5a1',
    messagingSenderId: '534458459636',
    projectId: 'notes-app-b63e5',
    authDomain: 'notes-app-b63e5.firebaseapp.com',
    storageBucket: 'notes-app-b63e5.firebasestorage.app',
    measurementId: 'G-XPFYV611S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQ5z3Rgw1kALafNGaUiyIIPdRgmn0kGo',
    appId: '1:534458459636:android:6d7aede38ecdbdf6e9c5a1',
    messagingSenderId: '534458459636',
    projectId: 'notes-app-b63e5',
    storageBucket: 'notes-app-b63e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDevSp5Cit9Vn-8p60Qy-gwUXcSWccrdpk',
    appId: '1:534458459636:ios:3a6f74d7e5a522efe9c5a1',
    messagingSenderId: '534458459636',
    projectId: 'notes-app-b63e5',
    storageBucket: 'notes-app-b63e5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDevSp5Cit9Vn-8p60Qy-gwUXcSWccrdpk',
    appId: '1:534458459636:ios:3a6f74d7e5a522efe9c5a1',
    messagingSenderId: '534458459636',
    projectId: 'notes-app-b63e5',
    storageBucket: 'notes-app-b63e5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );
}
